### ISSUE TITLE
get_protocol isn't working for several coins

### ISSUE THREAD

**Issue by M0ssy101** [the-praxs/DeFiLlama-Curl#3]
<img width="1032" alt="Screenshot 2022-05-18 at 17 57 02" src="https://user-images.githubusercontent.com/85117541/169038399-c47b13d0-3a1d-4620-9074-40c12b9d9e67.png">
<img width="866" alt="Screenshot 2022-05-18 at 17 57 23" src="https://user-images.githubusercontent.com/85117541/169038463-1c3c47a9-dac9-4a10-b00f-800673adf9d4.png">
 
These are the coins with the same issue so far. They were working fine until a few days ago, idk what changed. 
<img width="91" alt="Screenshot 2022-05-18 at 17 58 10" src="https://user-images.githubusercontent.com/85117541/169038613-9ea5b4c4-471c-4213-ac52-5eeb51ab029f.png">

**Comment by dot-agi** [comment]
Hi there,

The package has been updated to the latest endpoints and no longer uses the OO paradigm. You can find the latest docs for using the package at http://defillama-curl.readthedocs.io/
